storage:
  enabled: true
  storageClass: "do-block-storage"
  accessModes:
    - ReadWriteMany
  size: 10Gi

nfs:
  image:
    repository: boyroywax/nfs-server
    tag: latest
  service:
    enabled: true
    type: ClusterIP
    port: 2049

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

persistence:
  enabled: true
  existingClaim: ""
  accessModes:
    - ReadWriteMany
  size: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}