# OpenBao vault deployment values
# This file configures the OpenBao vault deployment on vault-labeled nodes

vault:
  name: openbao
  fullName: openbao-vault
  displayName: "OpenBao Vault"
  url: "https://openbao.org"

# Namespace configuration - vault namespace
namespace:
  create: true
  name: openbao-vault

# NFS configuration for vault storage - CRITICAL: Using boyroywax/nfs-server
nfs:
  image:
    repository: boyroywax/nfs-server
    tag: 1.0.0
    pullPolicy: IfNotPresent
  storage:
    size: 10Gi  # Storage for vault data
    storageClass: do-block-storage
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 1001
    privileged: true

# OpenBao vault configuration
openbao:
  image:
    repository: openbao/openbao
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  probes:
    readiness:
      enabled: true
      path: "/v1/sys/health?standbycode=200&perfstandbycode=200&drsecondarycode=200&sealedcode=200&uninitcode=200"
      port: 8200
      initialDelaySeconds: 30
      periodSeconds: 10
    liveness:
      enabled: true
      path: "/v1/sys/health?standbycode=200&perfstandbycode=200&drsecondarycode=200&sealedcode=200&uninitcode=200"
      port: 8200
      initialDelaySeconds: 60
      periodSeconds: 30
  
  # Vault configuration
  config:
    storage:
      file:
        path: "/vault/data"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true  # Will be handled by ingress TLS
    ui: true
    api_addr: "http://0.0.0.0:8200"
    cluster_addr: "http://0.0.0.0:8201"
    log_level: "Info"
    # disable_mlock removed - not supported in OpenBao

# Vault initialization job - disabled for manual control
vaultInit:
  enabled: false  # Set to true if you want auto-initialization
  image:
    repository: openbao/openbao
    tag: "latest"
    pullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  activeDeadlineSeconds: 300
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400

# Service configuration
service:
  type: ClusterIP
  port: 8200
  targetPort: 8200
  clusterPort: 8201
  targetClusterPort: 8201

# Ingress configuration with TLS - DISABLED for security
ingress:
  enabled: false  # Vault should not be exposed externally
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/client-max-body-size: "10m"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  host: "vault.layerwork.space"
  tls:
    enabled: true
    secretName: "openbao-vault-tls"

# DNS configuration
dns:
  domain: layerwork.space
  subdomain: vault

# Security context for vault container
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  fsGroup: 1001
  capabilities:
    add:
      - IPC_LOCK

# CRITICAL: Node selector for vault-labeled nodes
nodeSelector:
  node-role.kubernetes.io/vault: "true"

# CRITICAL: Node affinity for vault-labeled nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "node-role.kubernetes.io/vault"
          operator: In
          values:
          - "true"

# Tolerations for vault nodes
tolerations:
- key: "node-role.kubernetes.io/vault"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

# Labels
labels:
  app: openbao
  component: vault-server

# Annotations
annotations:
  vault.hashicorp.com/role: "openbao-vault"

# Persistent volume configuration
persistence:
  enabled: true
  size: 10Gi
  storageClass: do-block-storage
  accessModes:
    - ReadWriteOnce

# Optional: automatically enable userpass auth and seed users after deployment
userpassBootstrap:
  enabled: false
  mountPath: userpass
  vaultAddr: "http://openbao-vault-service:8200"
  waitTimeoutSeconds: 300
  tokenSecret:
    name: vault-bootstrap-token
    key: token
  users: []
  image:
    repository: openbao/openbao
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  activeDeadlineSeconds: 300
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
