{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-vault-ingress
  namespace: {{ include "openbao.namespace" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
    component: vault-service
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ include "openbao.hostname" . }}
    secretName: {{ include "openbao.tlsSecretName" . }}
  {{- end }}
  rules:
  - host: {{ include "openbao.hostname" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openbao-vault-service
            port:
              number: {{ .Values.service.port }}
{{- end }}
