{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openbao.namespace" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "openbao.namespace" . }}
    security.kubernetes.io/purpose: vault
  annotations:
    helm.sh/resource-policy: keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
{{- end }}
