apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbao.fullname" . }}-config
  namespace: {{ include "openbao.namespace" . }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
data:
  vault.hcl: |
    # UI
    ui = {{ .Values.vault.config.ui }}
    
    # Storage configuration
    {{- if .Values.vault.config.storage.file }}
    storage "file" {
      path = "{{ .Values.vault.config.storage.file.path }}"
    }
    {{- end }}
    
    # Listener configuration
    {{- if .Values.vault.config.listener.tcp }}
    listener "tcp" {
      address = "{{ .Values.vault.config.listener.tcp.address }}"
      tls_disable = {{ .Values.vault.config.listener.tcp.tls_disable }}
    }
    {{- end }}