apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbao.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openbao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openbao.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "openbao.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 1000
      containers:
        - name: openbao-vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: https-internal
              containerPort: 8201
              protocol: TCP
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://$(POD_IP):8200"
            - name: VAULT_CLUSTER_ADDR
              value: "https://$(POD_IP):8201"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "vault"
            - "server"
            - "-config=/vault/config/vault.hcl"
          volumeMounts:
            - name: config
              mountPath: /vault/config
              readOnly: true
            - name: vault-storage
              mountPath: /vault/file
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      volumes:
        - name: config
          configMap:
            name: {{ include "openbao.fullname" . }}-config
        - name: vault-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "openbao.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
      terminationGracePeriodSeconds: 30