apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openbao.fullname" . }}-network-policy
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openbao.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              access: vault
      ports:
        - protocol: TCP
          port: 8200
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: nfs-server
      ports:
        - protocol: TCP
          port: 2049