{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openbao.fullname" . }}-role
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openbao.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openbao.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openbao.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ include "openbao.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}